/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlbumList: typeof import('./src/components/AlbumList.vue')['default']
    ArtistItem: typeof import('./src/components/components/ArtistItem.vue')['default']
    AudioBox: typeof import('./src/components/components/PlayBarTmp/AudioBox.vue')['default']
    Bar: typeof import('./src/components/components/PlayBarTmp/Bar.vue')['default']
    Comments: typeof import('./src/components/components/Comments.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    Empty: typeof import('./src/components/components/Empty.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Lyrics: typeof import('./src/components/components/Lyrics.vue')['default']
    MiniBar: typeof import('./src/components/components/PlayBarTmp/MiniBar.vue')['default']
    MvList: typeof import('./src/components/MvList.vue')['default']
    PlayBar: typeof import('./src/components/components/PlayBarTmp/PlayBar.vue')['default']
    PlayList: typeof import('./src/components/PlayList.vue')['default']
    ProgressLine: typeof import('./src/components/components/ProgressLine.vue')['default']
    Reply: typeof import('./src/components/components/Reply.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SongList: typeof import('./src/components/SongList.vue')['default']
  }
}
